language: python
dist: trusty

os: osx
osx_image: xcode9.4
language: generic
env: TOXENV=py36
addons:
  homebrew:
    # update: true
    packages: python3.6
before_install:
  - pip3 install virtualenv
  - virtualenv -p python3 ~/venv
  - source ~/venv/bin/activate

addons:
  chrome: stable

before_install:
- sudo apt-get update
- sudo apt-get install python3

python:
  - "3.6"

install:
  - pip3 install pytest
  - pip3 install selenium
  - pip3 install urllib3==1.26.15

script:
  - pytest
