language: python

python:
  - "3.9"

install:
  - pip3 install pytest
  - pip3 install selenium
  - pip3 install webdriver-manager

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - pytest Demo.py
