language: python
dist: trusty
os: osx

addons:
  chrome: stable

before_install:
- sudo apt-get update
- sudo apt-get install python3

python:
  - "3.9"

install:
  - pip3 install pytest
  - pip3 install selenium
  - pip3 install urllib3==1.26.15

script:
  - pytest
