language: python
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  ⋮

python:
  - "3.6"

install:
  - pip3 install config
  - pip install -r requirements.txt

script:
  - pytest
