language: python
dist: trusty
sudo: false

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

python:
  - "3.9"

install:
  - pip3 install pytest
  - pip3 install selenium
  - pip3 install webdriver-manager
  - pip3 install urllib3==1.26.15

script:
  - pytest test_demo.py
